#!/usr/bin/env bash
# This script configures an loadBalancer
sudo apt-get update
apt-get install -y haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 100.26.120.253 check\n\tserver web2 100.26.216.235 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
