#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Maske sure that HAproxy can be managed via an init script

# Install HAproxy
sudo apt-get -y update
apt-get -y install haproxy

# Configure frontend & Backend
configString=\
"
frontend iamdharrenzug-frontend
         bind *:80
         mode http
         default_backend iamdharrenzug-backend
backend iamdharrenzug-backend
        balance roundrobin
        server 67572-web-01 54.175.69.64:80 check
        server 67572-web-02 35.175.63.85:80 check
"
echo "$configString" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable the HAproxy init script
newString="#EXTRAOPTS=\"-de -m 16\"\nENABLED=1"
sudo sed -i "s/#EXTRAOPTS=\"-de -m 16\"/$newString/" /etc/default/haproxy

sudo service haproxy start
